# Generated by Django 3.0.6 on 2020-05-14 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200514_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
