# Generated by Django 3.0.6 on 2020-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200515_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
