# Generated by Django 3.0.6 on 2020-05-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200515_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
