# Generated by Django 3.0.6 on 2020-05-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200515_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='username',
        ),
    ]
