# Generated by Django 3.0.6 on 2020-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_marks_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
