# Generated by Django 3.0.6 on 2020-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_marks_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='face_authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
