# Generated by Django 3.0.6 on 2020-05-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_face_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='face_authentication',
        ),
    ]
